project:
  type: book
  output-dir: _book

book:
  title: "Arch Linux Installation and Setup Personal Guide"
  author: Aditya Ranjan Shandilya
  date: last-modified

  reader-mode: true
  
  favicon: images/archlinux-logo.png
  site-url: https://Aditya-Shandilya.github.io/Arch-Installation-and-Setup/
  repo-url: https://github.com/Aditya-Shandilya/Arch-Installation-and-Setup/
  repo-branch: main
  repo-actions: [edit,issue]
  # downloads: [pdf,epub]

  chapters:
    - index.qmd
    - content/minimal_install_intro.qmd
    
format:
  html:
    theme: flatly
    code-fold: true
    code-tools: true
    csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
#   pdf:
#     documentclass: scrbook
# #    lof: true
# #    lot: true
#     toc: true    
#     geometry:
#       - top=30mm
#       - left=20mm
#       - heightrounded
#     hyperrefoptions:
#       - linktoc=all
#     colorlinks: true
#     linkcolor: "blue"
#     biblio-style: ieee
#     highlight-style: github
#     mainfont: "Calibri"
#     keep-tex: true
#     output-file: arch_linux_installation_guide 
#   epub:
#     theme: flatly
#     output-file: arch_linux_installation_guide

execute:
  freeze: auto